title: Pinel
description: "Blazingly fast code editor in Rust"
url: ""
baseurl: ""

theme: pinel-theme

collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
